name: CI

on:
  push:
    branches:
      - master
      - ci/**
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Update git submodules
      run: git submodule update --init --recursive
    - name: Build iOS
      run: xcodebuild -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12 Pro" -scheme "Harvest-SwiftUI-Gallery" build
